# User config
author: "Купи тачьку"
tagline: "Pineapple Certfied Jekyll Theme"
description: "Если нужна тачька, то обращайся к Максиму, он поможет..."
keywords: "Pineapple, Pineapple Pizza, Pineapple House"
email: "lolkek@cheburek.pl"
linkedin: "https://www.linkedin.com/"
twitter: "https://twitter.com/"
github: "https://github.com/"

# Site config
baseurl: "/pineapple"
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed